jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"

  # Security Realm for user authentication
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

        - id: "developer"
          password: "developer"

        - id: "viewer"
          password: "viewer"


  # Authorization Strategy
  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read
      

# Tool Configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github-credentials
              username: '${GIT_USER}'
              password: '${GIT_PAT}'
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub_id
              username: '${DOCKER_USER}'
              password: '${DOCKER_PAT}'
# Sample Job Configuration
jobs:
  - script: >
      pipelineJob('nginx-demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://${GIT_REPO}')
                }
                branch('main')
              }
            }
            lightweight()
          }
        }
      }
