apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2  # Dev uses 2 replicas instead of 1
  template:
    spec:
      containers:
        - name: my-app
          image: my-app:dev  # Different image for dev