kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base

patches:
- path: deployment-patch.yaml

images:
- name: my-app
  newName: damducthoai/test-01
  newTag: build-20
